package binary

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// TestILP32LayoutAgainstCompiler verifies the 32-bit layout — the one the
// archived player database is actually in — against a real compiler.
//
// It needs `gcc -m32`, which needs 32-bit libc headers (gcc-multilib on
// Debian and derivatives). Those are not installed everywhere, so the test
// skips rather than fails when they are missing, and says exactly what to
// install. Everything else about the 32-bit layout is checked indirectly:
// TestLayoutEngineMatchesTheCompiler shows the engine agrees with gcc at
// LP64, and TestILP32RecordSizeMatchesTheArchivedFile shows the ILP32 record
// size reproduces the archived file's recorded size.
//
// When it does run, it is the direct check: the same C declaration, compiled
// for the same model the data was written under, reporting its own offsets.
func TestILP32LayoutAgainstCompiler(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compiler check in short mode")
	}
	gcc, err := exec.LookPath("gcc")
	if err != nil {
		t.Skip("gcc not found; skipping the direct 32-bit layout check")
	}

	root := repoRoot(t)
	src := filepath.Join(root, "reference", "tools", "pfilelayout.c")
	if _, err := os.Stat(src); err != nil {
		t.Skipf("%s not found; skipping", src)
	}
	// conf.h is generated by the C tree's configure and is gitignored, so a
	// fresh checkout will not have it until that has been run.
	if _, err := os.Stat(filepath.Join(root, "reference", "moderncserver", "src", "conf.h")); err != nil {
		t.Skip("reference/moderncserver/src/conf.h not present; run its configure first")
	}

	bin := filepath.Join(t.TempDir(), "pfilelayout32")
	build := exec.Command(gcc, "-m32", "-std=gnu89", "-fcommon", "-w",
		"-I"+filepath.Join(root, "reference", "moderncserver", "src"),
		"-o", bin, src)
	if out, err := build.CombinedOutput(); err != nil {
		t.Skipf("cannot build 32-bit (install gcc-multilib to enable this check): %v\n%s", err, out)
	}

	out, err := exec.Command(bin).Output()
	if err != nil {
		t.Fatalf("running the 32-bit layout probe: %v", err)
	}

	var c cLayout
	if err := json.Unmarshal(out, &c); err != nil {
		t.Fatalf("parsing the probe's output: %v", err)
	}
	if c.LongSize != 4 || c.PointerSize != 4 {
		t.Fatalf("the probe did not build 32-bit: long=%d ptr=%d", c.LongSize, c.PointerSize)
	}

	l := computeLayout(ilp32)
	if l.Size != c.RecordSize {
		t.Errorf("ilp32 record size = %d, compiler says %d", l.Size, c.RecordSize)
	}
	for _, f := range c.Fields {
		name := f.Name
		switch {
		case name == "affected.1.type":
			continue // a stride probe, covered by TestAffectedElementStride
		case len(name) > len("affected.0.") && name[:len("affected.0.")] == "affected.0.":
			name = "affected." + name[len("affected.0."):]
		}
		got := l.at(name)
		if got.Offset != f.Offset || got.Size != f.Size {
			t.Errorf("ilp32 %s = offset %d size %d, compiler says offset %d size %d",
				f.Name, got.Offset, got.Size, f.Offset, f.Size)
		}
	}
}

// repoRoot walks up from the test's working directory to the module root.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for i := 0; i < 10; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatal("could not find the module root")
	return ""
}
