// Copyright (C) 2026 Dave O'Connor. Part of Disgracelands, a derivative work
// of CircleMUD (Copyright (C) 1993-2001 Jeremy Elson, the Trustees of the
// Johns Hopkins University and the CircleMUD Group), itself based on DikuMUD
// (Copyright (C) 1990, 1991). Use of this file is governed by the CircleMUD
// and DikuMUD licenses; see LICENSE. Non-commercial use only.

package main

import (
	"context"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"testing"

	"github.com/gerrowadat/disgracelands/internal/persist/dataversion"
	"github.com/gerrowadat/disgracelands/internal/persist/world"
	"github.com/gerrowadat/disgracelands/internal/persist/world/classic"
	worldyaml "github.com/gerrowadat/disgracelands/internal/persist/world/yaml"
)

// stockBinaryDir is examples/stock/binary from cmd/dlctl's own package
// directory — the real, checked-in fixture `import` (with no --type)'s own README
// (examples/stock/README.md) documents producing examples/stock/yaml
// from, used here rather than a synthetic one so this test exercises the
// same seven subsystems and the same real archive data every other
// importer's own tests do individually.
const stockBinaryDir = "../../examples/stock/binary"

// libImportFixtures is every checked-in binary/yaml pair `import` (with no --type)'s
// own tests hold to the same standard: regenerate yaml from binary, and
// it must match what is checked in byte for byte. examples/mini is the
// second entry, added once it existed — its own README has the story of
// what building it against these same tests actually caught (the room
// vnums needed to include game.MortalStartRoom, and a zone's yaml file
// only carries a mobile or object whose vnum falls inside that zone's own
// bot–top range).
var libImportFixtures = []struct {
	name      string
	binaryDir string
	yamlDir   string
}{
	{"stock", stockBinaryDir, "../../examples/stock/yaml"},
	{"mini", "../../examples/mini/binary", "../../examples/mini/yaml"},
	// examples/torture is the third, and the only one built to fail:
	// docs/proposals/yaml-only.md §5.1's deliberately hostile lib/,
	// generated by internal/fixtures/torture. Holding it to this same
	// standard is what makes it a corpus rather than a museum — a
	// conversion bug that only shows up on a bare carriage return or a
	// full board is a regression here and nowhere else.
	{"torture", "../../examples/torture/binary", "../../examples/torture/yaml"},
}

func TestImportRequiresBothDirs(t *testing.T) {
	if err := run([]string{"import"}); err == nil {
		t.Error("run([import]) with neither flag succeeded, want an error")
	}
	if err := run([]string{"import", "--from-dir", stockBinaryDir}); err == nil {
		t.Error("run([import --from-dir]) with no --to-dir succeeded, want an error")
	}
	if err := run([]string{"import", "--to-dir", t.TempDir()}); err == nil {
		t.Error("run([import --to-dir]) with no --from-dir succeeded, want an error")
	}
}

func TestImportConvertsEndToEnd(t *testing.T) {
	for _, fx := range libImportFixtures {
		t.Run(fx.name, func(t *testing.T) {
			to := t.TempDir()
			if err := run([]string{"import", "--from-dir", fx.binaryDir, "--to-dir", to}); err != nil {
				t.Fatalf("run([import]): %v", err)
			}

			// One file or directory per subsystem `import` (with no --type) wraps,
			// matching what the checked-in yaml/ itself already holds.
			for _, want := range []string{
				"world/zones.yaml",
				"state/clock.yaml",
				"state/houses.yaml",
				"config/names.yaml",
				"config/messages.yaml",
				"config/socials.yaml",
				"text/help/help.yaml",
				"text/credits",
				"text/motd",
			} {
				if _, err := os.Stat(filepath.Join(to, want)); err != nil {
					t.Errorf("expected %s to exist: %v", want, err)
				}
			}

			// players/ is produced only where there is a roster to
			// produce it from. Neither stock nor mini has anyone in
			// binary/ (a fresh stock install has none, and mini is
			// invented from scratch), and import --type=pfile does not
			// create an empty directory for zero characters — asserting
			// that rather than assuming it. torture does have a roster,
			// which is the whole reason it exists: it is the only
			// checked-in fixture in this repository with a player file,
			// a rent file, an alias file, boards, mail, houses or bans
			// in it at all (docs/proposals/yaml-only.md §5.1).
			_, err := os.Stat(filepath.Join(to, "players"))
			if fx.name == "torture" {
				if err != nil {
					t.Errorf("players/ is missing for a fixture with a roster: %v", err)
				}
			} else if !os.IsNotExist(err) {
				t.Errorf("players/ exists with an empty roster to import: %v", err)
			}

			// The stamp is this build's release version, and a test
			// binary has none (docs/design/data-format-versioning.md
			// §6), so `import` writes no stamp at all here rather
			// than inventing a number. A released dlctl is what
			// produces one; that half is dataversion's own tests.
			if _, err := os.Stat(filepath.Join(to, dataversion.FileName)); !os.IsNotExist(err) {
				t.Errorf("%s was written by a build with no release version: %v", dataversion.FileName, err)
			}
		})
	}
}

func TestImportMatchesTheCheckedInExamples(t *testing.T) {
	// Each yaml/ is its own binary/ converted exactly this way (both
	// READMEs say so) — regenerating it and diffing against what is
	// checked in is what proves that claim rather than assuming it, and
	// catches the fixture and the command drifting apart from each other
	// silently.
	for _, fx := range libImportFixtures {
		t.Run(fx.name, func(t *testing.T) {
			to := t.TempDir()
			if err := run([]string{"import", "--from-dir", fx.binaryDir, "--to-dir", to}); err != nil {
				t.Fatalf("run([import]): %v", err)
			}

			var mismatches []string
			err := filepath.WalkDir(fx.yamlDir, func(path string, d os.DirEntry, err error) error {
				if err != nil || d.IsDir() {
					return err
				}
				rel, err := filepath.Rel(fx.yamlDir, path)
				if err != nil {
					return err
				}
				if rel == dataversion.FileName {
					return nil // not produced by a fresh checkout of the fixture itself
				}
				want, err := os.ReadFile(path)
				if err != nil {
					return err
				}
				got, err := os.ReadFile(filepath.Join(to, rel))
				if err != nil {
					mismatches = append(mismatches, rel+": "+err.Error())
					return nil
				}
				if string(got) != string(want) {
					mismatches = append(mismatches, rel+": content differs")
				}
				return nil
			})
			if err != nil {
				t.Fatalf("walking %s: %v", fx.yamlDir, err)
			}
			for _, m := range mismatches {
				t.Error(m)
			}
		})
	}
}

// TestCopyGameConfigCarriesTheTuning. The game tuning lives in the data
// directory now (docs/design/data-format.md §6), which makes it something a
// conversion can lose: a lib/ with free_rent turned off that came out the
// other side without its config/game.yaml would be a server quietly back on
// config.c's defaults, with nothing in the output saying so. It is copied
// rather than converted because there is nothing to convert — the file is
// this project's own yaml in either format.
func TestCopyGameConfigCarriesTheTuning(t *testing.T) {
	from, to := t.TempDir(), t.TempDir()
	if err := os.MkdirAll(filepath.Join(from, "config"), 0o700); err != nil {
		t.Fatal(err)
	}
	const body = "free_rent: false\n"
	if err := os.WriteFile(filepath.Join(from, "config", "game.yaml"), []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	copied, err := copyGameConfig(from, to)
	if err != nil {
		t.Fatalf("copyGameConfig: %v", err)
	}
	if !copied {
		t.Error("copyGameConfig reported no file, want the one that is there")
	}
	got, err := os.ReadFile(filepath.Join(to, "config", "game.yaml"))
	if err != nil {
		t.Fatalf("reading the copy: %v", err)
	}
	if string(got) != body {
		t.Errorf("the copy = %q, want %q", got, body)
	}
}

// TestCopyGameConfigWithNoneIsNotAnError: every stock and archived lib/ in
// existence has no config/game.yaml, so importing one must not be a failure
// — and must not leave an empty config/ behind either, since names/messages/
// socials are what own that directory's existence.
func TestCopyGameConfigWithNoneIsNotAnError(t *testing.T) {
	to := t.TempDir()
	copied, err := copyGameConfig(t.TempDir(), to)
	if err != nil {
		t.Fatalf("copyGameConfig with no file: %v", err)
	}
	if copied {
		t.Error("copyGameConfig reported a file where there was none")
	}
	if _, err := os.Stat(filepath.Join(to, "config")); !os.IsNotExist(err) {
		t.Errorf("config/ was created for a file that does not exist: %v", err)
	}
}

// TestImportCarriesTheMiniWorldAcross: a converted archive keeps the small
// world it already had.
//
// `--mini-mud` is the C's `-m`, and in a classic lib/ it means "read
// index.mini instead of index in each of the five world subdirectories".
// The yaml format's answer is world/sets.yaml's "mini" subset
// (docs/design/data-format.md §4), and until issue #274 nothing wrote it
// and nothing read it, so the flag was silently inert on the only format
// the server runs.
//
// Every fixture here has index.mini files, so every one of them should come
// out of a full import with a sets.yaml naming the same zones — checked
// against the classic reader's own view of the mini world rather than
// against a number written down here, so that a fixture gaining a zone does
// not need this test edited.
func TestImportCarriesTheMiniWorldAcross(t *testing.T) {
	for _, fx := range libImportFixtures {
		t.Run(fx.name, func(t *testing.T) {
			src, err := classic.New(world.Config{Dir: filepath.Join(fx.binaryDir, "world"), Mini: true})
			if err != nil {
				t.Fatal(err)
			}
			defer func() { _ = src.Close() }()
			mini, err := src.Load(context.Background())
			if err != nil {
				t.Skipf("%s has no mini world to carry across: %v", fx.name, err)
			}
			want := make([]int32, 0, len(mini.Zones))
			for _, z := range mini.Zones {
				want = append(want, int32(z.Vnum))
			}
			if len(want) == 0 {
				t.Skipf("%s has an empty mini world", fx.name)
			}
			sort.Slice(want, func(i, j int) bool { return want[i] < want[j] })

			to := t.TempDir()
			if err := run([]string{"import", "--from-dir", fx.binaryDir, "--to-dir", to}); err != nil {
				t.Fatalf("run([import]): %v", err)
			}

			// Through the loader, not by reading the file: what matters is
			// that `dlmud --mini-mud` on this directory loads that world.
			ysrc, err := worldyaml.New(world.Config{Dir: filepath.Join(to, "world"), Mini: true})
			if err != nil {
				t.Fatal(err)
			}
			got, err := ysrc.Load(context.Background())
			if err != nil {
				t.Fatalf("loading the converted mini world: %v", err)
			}
			var gotVnums []int32
			for _, z := range got.Zones {
				gotVnums = append(gotVnums, int32(z.Vnum))
			}
			sort.Slice(gotVnums, func(i, j int) bool { return gotVnums[i] < gotVnums[j] })

			if !slices.Equal(gotVnums, want) {
				t.Errorf("converted mini world has zones %v, the classic one has %v", gotVnums, want)
			}

			// And the point of the whole exercise: it is smaller than the
			// full one. A mini world identical to the full world would pass
			// every assertion above and be exactly the bug #274 was.
			full, err := worldyaml.New(world.Config{Dir: filepath.Join(to, "world")})
			if err != nil {
				t.Fatal(err)
			}
			fullWorld, err := full.Load(context.Background())
			if err != nil {
				t.Fatal(err)
			}
			if len(fullWorld.Zones) > len(got.Zones) && len(got.Rooms) >= len(fullWorld.Rooms) {
				t.Errorf("the mini world has %d room(s) and the full one %d, from %d zones against %d: the subset is not subsetting",
					len(got.Rooms), len(fullWorld.Rooms), len(got.Zones), len(fullWorld.Zones))
			}
		})
	}
}
